"""
Claim form PDF generation for ClaimPilot v2.4.0.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Dict

from fpdf import FPDF

from config.settings import EXPORT_DISCLAIMER
from config.states import get_state, tier_label


def generate_claim_form_pdf(
    intake: Dict[str, Any],
    state_abbr: str,
) -> bytes:
    """Generate a claim form PDF. Returns PDF bytes."""
    state = get_state(state_abbr)
    coverage = tier_label(state_abbr) if state else "Unknown"
    state_name = state.name if state else state_abbr

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Coverage status header
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Coverage Status: {coverage}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, f"Generated by ClaimPilot on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Title
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Small Claims Court - {state_name}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "CLAIM FORM", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Claimant section
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "PLAINTIFF / CLAIMANT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Name: {intake.get('claimant_name', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Address: {intake.get('claimant_address', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Phone: {intake.get('claimant_phone', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Email: {intake.get('claimant_email', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Defendant section
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "DEFENDANT / RESPONDENT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Name: {intake.get('respondent_name', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Address: {intake.get('respondent_address', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Claim details
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "CLAIM DETAILS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Claim Type: {intake.get('claim_type', 'small_claims')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date of Incident: {intake.get('incident_date', '')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Amount Claimed: ${intake.get('amount_claimed', 0):,.2f}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "DESCRIPTION OF CLAIM", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, intake.get("description", ""))
    pdf.ln(3)

    outcome = intake.get("desired_outcome", "")
    if outcome:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "DESIRED OUTCOME", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, outcome)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4, EXPORT_DISCLAIMER)

    return pdf.output()
