"""
Demand letter PDF generation for ClaimPilot v2.4.0.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Dict

from fpdf import FPDF

from config.settings import EXPORT_DISCLAIMER
from config.states import get_state, tier_label


def generate_demand_letter_pdf(
    intake: Dict[str, Any],
    state_abbr: str,
) -> bytes:
    """Generate a demand letter PDF. Returns PDF bytes."""
    state = get_state(state_abbr)
    coverage = tier_label(state_abbr) if state else "Unknown"

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header with coverage status
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Coverage Status: {coverage}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, f"Generated by ClaimPilot on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Date
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, date.today().strftime("%B %d, %Y"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Respondent
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, intake.get("respondent_name", "[Respondent Name]"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    resp_addr = intake.get("respondent_address", "[Respondent Address]")
    for line in resp_addr.split("\n"):
        pdf.cell(0, 6, line.strip(), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Subject
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "DEMAND LETTER", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Body
    pdf.set_font("Helvetica", "", 11)
    claimant = intake.get("claimant_name", "[Your Name]")
    amount = intake.get("amount_claimed", 0)
    description = intake.get("description", "[Claim description]")
    incident_date = intake.get("incident_date", "[Date]")

    body = (
        f"Dear {intake.get('respondent_name', 'Sir/Madam')},\n\n"
        f"I, {claimant}, am writing to formally demand payment in the amount of "
        f"${amount:,.2f} for the following matter:\n\n"
        f"{description}\n\n"
        f"This incident occurred on or about {incident_date}.\n\n"
    )

    resolution = intake.get("resolution_attempted", "")
    if resolution:
        body += f"I have previously attempted to resolve this matter: {resolution}\n\n"

    body += (
        f"I demand that you pay the full amount of ${amount:,.2f} within thirty (30) days "
        f"of the date of this letter. If I do not receive payment by that date, I intend "
        f"to pursue all available legal remedies, including filing a claim in small claims court.\n\n"
        f"Sincerely,\n{claimant}"
    )

    pdf.multi_cell(0, 6, body)

    # Disclaimer footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4, EXPORT_DISCLAIMER)

    return pdf.output()
