"""
Evidence index PDF generation for ClaimPilot v2.4.0.

Generates a professional evidence index with:
- Numbered exhibit list in tabular format
- File metadata (name, type, size, date)
- Description column
- Summary statistics
"""

from __future__ import annotations

from datetime import date
from typing import Any, Dict, List

from fpdf import FPDF

from config.settings import EXPORT_DISCLAIMER
from config.states import get_state, tier_label


def _format_file_size(size_bytes: int) -> str:
    """Format file size in human-readable form."""
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.1f} MB"


def generate_evidence_index_pdf(
    evidence_items: List[Dict[str, Any]],
    state_abbr: str,
) -> bytes:
    """Generate an evidence index PDF. Returns PDF bytes."""
    state = get_state(state_abbr)
    coverage = tier_label(state_abbr)
    state_name = state.name if state else state_abbr

    pdf = FPDF()
    pdf.add_page("L")  # Landscape for wider table
    pdf.set_auto_page_break(auto=True, margin=15)

    # ---- Header ----
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "EVIDENCE INDEX", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"State of {state_name} | Coverage: {coverage}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"Generated by ClaimPilot on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(3)
    pdf.line(10, pdf.get_y(), pdf.w - 10, pdf.get_y())
    pdf.ln(5)

    if not evidence_items:
        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 7, "No evidence items have been submitted.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, (
            "To strengthen your case, consider gathering:\n"
            "- Contracts, receipts, or invoices\n"
            "- Photographs or video evidence\n"
            "- Written correspondence (emails, letters, text messages)\n"
            "- Witness statements\n"
            "- Expert reports or estimates"
        ))
    else:
        # Column widths for landscape (total ~257mm usable)
        col_num = 12
        col_exhibit = 25
        col_label = 50
        col_filename = 45
        col_type = 30
        col_size = 22
        col_date = 25
        col_desc = pdf.w - 20 - col_num - col_exhibit - col_label - col_filename - col_type - col_size - col_date

        # Table header
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(col_num, 7, " #", border=1, fill=True)
        pdf.cell(col_exhibit, 7, " Exhibit", border=1, fill=True)
        pdf.cell(col_label, 7, " Label / Title", border=1, fill=True)
        pdf.cell(col_filename, 7, " File Name", border=1, fill=True)
        pdf.cell(col_type, 7, " Type", border=1, fill=True)
        pdf.cell(col_size, 7, " Size", border=1, fill=True)
        pdf.cell(col_date, 7, " Date Added", border=1, fill=True)
        pdf.cell(col_desc, 7, " Description", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(255, 255, 255)

        pdf.set_font("Helvetica", "", 8)
        for i, item in enumerate(evidence_items, 1):
            # Alternate row colors
            if i % 2 == 0:
                pdf.set_fill_color(245, 245, 245)
            else:
                pdf.set_fill_color(255, 255, 255)

            exhibit = f"Exhibit {chr(64 + i)}" if i <= 26 else f"Exhibit {i}"
            label = (item.get("label", "") or "")[:28]
            filename = (item.get("file_name", "") or "")[:25]
            ftype = (item.get("file_type", "") or "").replace("application/", "")[:15]
            size = _format_file_size(item.get("file_size_bytes", 0))
            date_str = (item.get("date_added", "") or "")[:10]
            desc = (item.get("description", "") or "")[:30]

            pdf.cell(col_num, 6, f" {i}", border=1, fill=True)
            pdf.cell(col_exhibit, 6, f" {exhibit}", border=1, fill=True)
            pdf.cell(col_label, 6, f" {label}", border=1, fill=True)
            pdf.cell(col_filename, 6, f" {filename}", border=1, fill=True)
            pdf.cell(col_type, 6, f" {ftype}", border=1, fill=True)
            pdf.cell(col_size, 6, f" {size}", border=1, fill=True)
            pdf.cell(col_date, 6, f" {date_str}", border=1, fill=True)
            pdf.cell(col_desc, 6, f" {desc}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_fill_color(255, 255, 255)

    pdf.ln(5)

    # ---- Summary ----
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Total evidence items: {len(evidence_items)}", new_x="LMARGIN", new_y="NEXT")

    if evidence_items:
        total_size = sum(item.get("file_size_bytes", 0) for item in evidence_items)
        pdf.cell(0, 6, f"Total file size: {_format_file_size(total_size)}", new_x="LMARGIN", new_y="NEXT")

        types = set(item.get("file_type", "unknown") for item in evidence_items)
        pdf.cell(0, 6, f"File types: {', '.join(sorted(types))}", new_x="LMARGIN", new_y="NEXT")

    # ---- Certification ----
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, (
        "I certify that the above is a true and complete index of all evidence "
        "I intend to present in support of my claim."
    ))
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Signature: ________________________________________     Date: _______________", new_x="LMARGIN", new_y="NEXT")

    # ---- Disclaimer ----
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 7)
    pdf.multi_cell(0, 4, EXPORT_DISCLAIMER)

    return pdf.output()
