"""
Evidence index PDF generation for ClaimPilot v2.4.0.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Dict, List

from fpdf import FPDF

from config.settings import EXPORT_DISCLAIMER
from config.states import tier_label


def generate_evidence_index_pdf(
    evidence_items: List[Dict[str, Any]],
    state_abbr: str,
) -> bytes:
    """Generate an evidence index PDF. Returns PDF bytes."""
    coverage = tier_label(state_abbr)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Coverage header
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Coverage Status: {coverage}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, f"Generated by ClaimPilot on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Title
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "EVIDENCE INDEX", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    if not evidence_items:
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 7, "No evidence items have been submitted.", new_x="LMARGIN", new_y="NEXT")
    else:
        # Table header
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(15, 7, "#", border=1)
        pdf.cell(55, 7, "Label", border=1)
        pdf.cell(45, 7, "File Name", border=1)
        pdf.cell(35, 7, "Type", border=1)
        pdf.cell(30, 7, "Date Added", border=1, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        for i, item in enumerate(evidence_items, 1):
            pdf.cell(15, 6, str(i), border=1)
            pdf.cell(55, 6, item.get("label", "")[:30], border=1)
            pdf.cell(45, 6, item.get("file_name", "")[:25], border=1)
            pdf.cell(35, 6, item.get("file_type", "")[:20], border=1)
            date_str = item.get("date_added", "")[:10]
            pdf.cell(30, 6, date_str, border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Total evidence items: {len(evidence_items)}", new_x="LMARGIN", new_y="NEXT")

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4, EXPORT_DISCLAIMER)

    return pdf.output()
