"""
Application-wide settings for ClaimPilot v2.4.0.
"""

APP_NAME = "ClaimPilot"
APP_VERSION = "2.4.0"
APP_TAGLINE = "Your guided path through the small-claims process"

LEGAL_DISCLAIMER = (
    "ClaimPilot is an informational tool, not a law firm. "
    "No attorney-client relationship is formed through use of this application. "
    "ClaimPilot does not provide legal advice. Consult a licensed attorney "
    "for advice specific to your situation."
)

ATTORNEY_MARKETPLACE_DISCLAIMER = (
    "Not a law firm. No attorney-client relationship is formed through this app. "
    "Attorney listings are provided for informational purposes only. "
    "You should independently verify any attorney's credentials and suitability."
)

EXPORT_DISCLAIMER = (
    "This document package was generated by ClaimPilot, an informational tool. "
    "It does not constitute legal advice. The contents should be reviewed by "
    "a qualified attorney before filing with any court or sending to any party. "
    "Coverage status and source verification details are included in this package."
)

REFUND_PLACEHOLDER = (
    "[REFUND POLICY PLACEHOLDER]\n"
    "Refund terms to be finalized before public launch. "
    "Contact support@claimpilot.example.com for questions."
)

SUPPORT_EMAIL = "support@claimpilot.example.com"

PRIVACY_SUMMARY = (
    "ClaimPilot collects only the information you provide in the intake form. "
    "Your data is stored locally in your browser session and is not transmitted "
    "to third parties unless you explicitly export or share it. "
    "You may delete all your data at any time using the 'Delete My Data' feature."
)
